# Generated by Django 5.2.5 on 2025-08-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
